version: "3.9"
services:
  mysqlss:
    image: mysql
    ports:
      - "27000:27000"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=pruebaDocker
    volumes:
      - mysql_data:/var/lib/mysql
    command: ["bash", "-c", "echo 'CREATE TABLE IF NOT EXISTS animales (id INT AUTO_INCREMENT PRIMARY KEY, tipo VARCHAR(255),estado VARCHAR(255));' | mysql -h mysqlss -u root -p1234 pruebaDocker"]
  granja: 
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysqlss
volumes:
  mysql_data: